version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
