apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-webdav-server.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-webdav-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.basicAuth.existingSecret }}
  BASIC_USERS: {{ .Values.basicAuth.users | quote }}
  {{- end }}
  {{- if not .Values.ldap.existingSecret }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  {{- end }}
  {{- if not .Values.oauth.existingSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
  {{- end }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretAccessKey | quote }}
  AZURE_STORAGE_KEY: {{ .Values.storage.azure.key | quote }}
