apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-webdav-server.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-webdav-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  BASIC_USERS: {{ .Values.basicAuth.users | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretAccessKey | quote }}
